language: java
sudo: false

before_install:
  - rvm install 2.3.1
  - rvm use 2.3.1
  - gem install hiptest-publisher
  - "hiptest-publisher -c cucumber-java.conf --only=features,step_definitions --test-run-id=397616"

script:
  - mvn test

after_script:
  - hiptest-publisher -c cucumber-java.conf --push=target/cuke-results.json --test-run-id=397616
